### ISSUE TITLE
Automatically sorts by key

### ISSUE THREAD

**Issue by jameswlane** [gildas-lormeau/JSONView-for-Chrome#44]
The plugin automatically sorts the information by their key vs just showing how it is output.
I would think as a developer this shouldn't be default or a way to disable it.
I spend several hours today wondering why asort() wasn't working for my array and come to find out the plugin was sorting the output vs showing the exact output.

**Comment by KyleFromOhio** [comment]
I am having same issue. 

ISSUE: The JSON arrays are being "re-sorted" before being displayed. 
SOLUTION: The items in an array should display in the order they are provided.

**Comment by Ma-ve** [comment]
Bump. This also had me baffled for several hours. Please look into this.

**Comment by daverogers** [comment]
Agreed. Luckily I didn't spend too much time bashing my head trying to figure it out. This default behavior is a head scratcher because most developers need arrays in a particular order, so seeing it sorted differently than how I'm programming it to sort is odd.

**Comment by CrazyTim** [comment]
Yes agreed, although it doesn't look like this project is active, sorting should be off by default. Provide the option to sort if you like, but we need to be confident the data has not been modified in any way by the plugin.

I had been back and forth with developers thinking they were sorting, but as it turns out my results were sorted! lol.

**Comment by Traxo7** [comment]
Any updates on this?
Is there any fork that resolved this?
